### ISSUE TITLE
授权后跳转回mainactivity时会报错

### ISSUE THREAD

**Issue by e-hai** [zubinxiong/DC4Android#1]
我使用你的工程，在webview授权后，跳转回mainactivity时会报错

**Comment by zubinxiong** [comment]
- 按照正常的 OAuth2.0 登录，在我传递参数到 AuthActivity 这个 webview 后，你登录成功后正常的话系统应该重定向至我在 API 申请时填写的跳转链接 your://abc.com + 系统返回的 code

- 然后我在 webview 中拦截了以 your://  开头的协议，将 code 返回并再次请求获取 accesstoken

- 我测试过登录成功的话系统并没有跳转至我填写的链接，而是跳转会了首页，这也是登录不成功的原因

- 正常的 oauth2.0 认证就是这样一种流程，之前 diycode.cc 的站长也说过他在改版，网站里面的 api 不稳定，我也是因为这个问题没有继续开发，建议等官方的 api 稳定后再开发

**Comment by zubinxiong** [comment]
这张图是我之前总结的流程，你可以参考下

![image](https://cloud.githubusercontent.com/assets/7650970/18379668/501cfc14-76a6-11e6-9247-fe52abcc0172.png)

**Comment by e-hai** [comment]
非常感谢你的回答！
嗯嗯，我看过了文章，但是有个问题想请教下： “API 申请时填写的跳转链接” 是否可以随便填写，即实际上并没有该网址。在正常的OAuth2.0流程下，论坛会不会先去认证是否存在该网址，才会返回结果呢？

**Comment by zubinxiong** [comment]
- 我把上面乱填的地址改成我自己的网站就能够正常跳转了，同时也返回了带code 的链接
- 测试的时候第一次填写发现要填https, 第二次又不用了，有些奇怪，不太清除 oauth2.0 是否强制需要
- 如果没有自己的网站做跳转，其实可以用github page 或者随便用个 https 的网站比如百度之类的，只是做拦截使用，但是不太清楚这样会不会有安全隐患。

-----

如果你要测试可以做下面的操作
-  MyConstants 里面的链接改成  https://www.baidu.com/
- AuthActivity 里面改成 url.startsWith("https://www.baidu.com/")

- 注意上面这部分都是正确的，到获取 [token](http://www.diycode.cc/oauth/token) 还是会异常，这个是它们网站的问题，我们是无法解决的
----
以上都是测试过的，这个 issues 我就先关了
